#output "consul_servers_public_ip" {
#    value = aws_instance.consul_servers.*.public_ip
#}

#output "jenkins_server_public_ip" {
#    value = aws_instance.jenkins_server.public_ip
#}

#output "jenkins_agents_private_ip" {
#    value = aws_instance.jenkins_agents.*.private_ip
#}

#output "cluster_id" {
#  description = "EKS cluster ID."
#  value       = module.eks.cluster_id
#}

#output "cluster_endpoint" {
#  description = "Endpoint for EKS control plane."
#  value       = module.eks.cluster_endpoint
#}

#output "cluster_security_group_id" {
#  description = "Security group ids attached to the cluster control plane."
#  value       = module.eks.cluster_security_group_id
#}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

#output "config_map_aws_auth" {
#  description = "A kubernetes configuration to authenticate to this EKS cluster."
#  value       = module.eks.config_map_aws_auth
#}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

#output "consul_servers" {
#  value = aws_instance.consul_server.*.public_ip
#}

